project:
  type: website
  output-dir: docs

website:
  title: "Mikyas Duga"
  navbar:
    
  
    pinned: true
    
    
    right:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Resume"
        href: resume/index.qmd

format:
  html:
    theme: 
      light: [sandstone, mycustom.scss]
      dark: [solar, mycustom_dark.scss]
    css: styles.scss
    # css: styles.css
    toc: false
    page-layout: full

editor: visual

