project:
  type: website
  output-dir: docs

website:
  title: "Mikyas Duga"
  navbar:
  
    pinned: true
    
    
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Resume"
        href: resume/index.qmd

format:
  html:
    theme: 
      light: [zephyr, mycustom.scss]
    css: html/styles.scss
    # css: styles.css
    toc: false
    page-layout: full

editor: visual

